# prettier-ignore
name: Laravel
on: push
jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          ref: "laravel"
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
      - name: Print to console
        run: echo Hello World!
      - name: Install PHP dependencies
        run: composer install
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile
      - name: Build Node.js dependencies
        run: yarn build
      - name: Migrate DB
        run: php artisan migrate --force
