# prettier-ignore
name: Laravel
on: push
jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    services:
      # mysql-service Label used to access the service container
      mysql:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
          ## Accessing to Github secrets, where you can store your configuration
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: postjob_test
        ## map the "external" 3306 port with the "internal" 3306
        ports:
          - 3306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          ref: "laravel"
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
      - name: Print to console
        run: echo Hello World!
      - name: Install PHP dependencies
        run: composer install
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile
      - name: Build Node.js dependencies
        run: yarn build
      - name: print env file 
        run: cat .env.testing
      - name: Migrate DB
        run: php artisan migrate --force
